# Exemple de configuration pour le MVP iObeya → GitHub Projects
grist:
  api_url: "http://localhost:8484/"
  api_token: "grist_api_token_example"
  default_doc_id: "exampleDoc123"
  default_epic_table: "Epics"
  default_feature_table: "Features"

iobeya:
  base_url: "https://iobeya.example.com"
  token: "iobeya_token_example"
  types_card_features: ["Feature", "Enabler"] # Définit les types de cartes iObeya à synchroniser

github:
  project_id: "example_project_v2_node_id"
  token_env_var: "github_token_example"
  organizations:
    - my-org-example
    - innovation-lab
    - ministry-digital

mapping:
  states:
    Funnel: "Proposed"
    Analyzing: "In Review"
    Implementing: "In Progress"
    Validating: "In QA"
    Done: "Done"

  fields:
    feature_key: "Feature Key"
    state: "State"
    wsjf: "WSJF"
    pi: "PI"
    owner: "Owner"
    tags: "Tags"
    last_sync_at: "Last Sync At"

run:
  output_dir: "data"
  storage_path: "data/id_map.json"
